version: '3.8'

services:
  db:
    image: postgres:15
    container_name: el-cliente-db
    environment:
      POSTGRES_DB: el_cliente
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./select.sql:/docker-entrypoint-initdb.d/select.sql
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d el_cliente"]
      interval: 10s
      timeout: 5s
      retries: 5 